import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      ><div className="flex justify-between m-5 p-6 items-center bg-zinc-500">
              <Link href = "/">Logo</Link>
        <nav >
          <ul className="flex divide-x-8 p-1 m-1 rounded shadow shadow-orange-300  bg-white/50 ">
            <li>
              <Link href ="/">Home</Link>
            </li>
            <li>
              <Link href ="/post">Post</Link>
            </li>
          </ul>
        </nav>
       </div>
        {children}
      </body>
    </html>
  );
}
